### ISSUE TITLE
Quick start can't work well

### ISSUE THREAD

**Issue by flyingzl** [Andr3wHur5t/react-native-route-navigator#1]
Quick start can't work well,  could you make it work well? for example, some required classes are missing.. .. If you can create an example, it would be wonderfull :smile: 

``` js
var React = require('react-native');
var {
  AppRegistry,
  Text,
  View,
  Navigator,
  TouchableHighlight
} = React;
```

**Comment by Andr3wHur5t** [comment]
I've fixed the example, it should work now. I'll upload a example gif once I have better connection.
