### ISSUE TITLE
Warning re initialRouteStack

### ISSUE THREAD

**Issue by patkaiist** [Andr3wHur5t/react-native-route-navigator#4]
The following warning comes up consistently, even if taking the code from your example directly without modifications.

```
Warning: Failed propType: Invalid prop `initialRouteStack[0]` of type `string` supplied 
to `Navigator`, expected `object`. Check the render method of `RouteNavigator`
```

This is on Android 4.1.2.

**Comment by Andr3wHur5t** [comment]
You can fix that by using this `navigator.push({name: "/page2/"})` instead of `navigator.push('/page2/')`.

The warning shouldn't effect the app but thats how you can work around it.

**Comment by patkaiist** [comment]
Thanks!
